name: Linux x86_64 GCC 12

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aeonengine/linux_x86_64:gcc12
    env:
      CONAN_REVISIONS_ENABLED: 1
      JOB_COUNT: 2

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Conan remote
        run: conan config install remotes.json

      - name: Conan install
        run: conan install . -of build --profile:host=./dep/devops/Conan/profiles/linux/gcc12_x86_64_debug --profile:build=./dep/devops/Conan/profiles/linux/gcc12_x86_64_debug

      - name: Cmake
        run: cmake . -B build -DCMAKE_INSTALL_PREFIX=$(pwd)/build/install -DCMAKE_BUILD_TYPE=Debug -DAEON_ENABLE_CONAN_INTEGRATION=0

      - name: Build
        run: cmake --build build -- -j$JOB_COUNT

      - name: Test
        run: ctest --test-dir build
