name: Windows x86_64 VS2022

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      CONAN_REVISIONS_ENABLED: 1

    steps:
      - name: Conan install
        run: python -m pip install conan

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Conan remote
        run: conan config install remotes.json

      - name: Conan install
        run: |
            conan install . -of build --profile:host=./dep/devops/Conan/profiles/windows/msvc2022_x86_64_debug --profile:build=./dep/devops/Conan/profiles/windows/msvc2022_x86_64_debug
            conan install . -of build --profile:host=./dep/devops/Conan/profiles/windows/msvc2022_x86_64_release --profile:build=./dep/devops/Conan/profiles/windows/msvc2022_x86_64_release

      - name: Cmake
        run: cmake . -B build -G "Visual Studio 17 2022" -T host=x64 -A x64 -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_INSTALL_PREFIX=%CD%/build/install -DAEON_ENABLE_CONAN_INTEGRATION=0

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: ctest --test-dir build -C Debug
